name: Tag Logger

on:
  push:
    branches:
      - main

jobs:
  tag_adapter:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: Tag logger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.ACCESS_TOKEN }}"
          ref: "main"

      - name: Files modified
        id: check
        uses: tj-actions/changed-files@v22.2
        with:
          files: |
            ./internal/**
            ./*.go
            ./go.mod
            ./go.sum

      - name: Should skip
        if: steps.check.outputs.any_changed != 'true'
        run: exit 78

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install commitizen
        run: pip install -U commitizen

      - id: cz
        name: Create bump and changelog
        working-directory: ${{ matrix.module }}
        run: |
          python -m pip install -U commitizen
          cz bump --changelog --yes
          export REV=`cz version --project`
          echo "version=$REV" >> $GITHUB_OUTPUT

      - name: Push changes
        uses: Woile/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          tags: "true"
          branch: "main"

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"